{"name": "test_app_login[13812345678-246810]", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "self = <scripts.test05_app_login.TestAppLogin object at 0x000001E27144C828>, phone = '13812345678'\ncode = '246810'\n\n    @pytest.mark.parametrize(('phone','code'),read_yaml('app_login.yaml'))\n    def test_app_login(self,phone,code):\n        self.login.page_app_login(phone,code)\n        try:\n            # 断言\n            assert self.login.page_is_login_success()\n        except Exception as e:\n            # 日志\n            log.error(e)\n            # 截图\n            self.login.base_get_img()\n        # 抛出异常\n>       raise\nE       RuntimeError: No active exception to reraise\n\nscripts\\test05_app_login.py:31: RuntimeError"}, "attachments": [{"name": "log", "source": "a56daba9-f7a2-48a5-a667-276632f85b41-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "phone", "value": "'13812345678'"}, {"name": "code", "value": "'246810'"}], "start": 1595837806421, "stop": 1595837832543, "uuid": "3c39daaa-b3c6-487a-8f3c-cd8067c97e3b", "historyId": "dff910e59219f10fae5fdc78ef383a70", "testCaseId": "ec2933d9e11d0cbb035e36410d90b36e", "fullName": "scripts.test05_app_login.TestAppLogin#test_app_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test05_app_login"}, {"name": "subSuite", "value": "TestAppLogin"}, {"name": "host", "value": "DESKTOP-IL3MDFO"}, {"name": "thread", "value": "12844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test05_app_login"}]}