{"name": "test_mp_login[13812345678-246810-叫我老]", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'attach_type'", "trace": "self = <scripts.test01_mp_login.TestMpLogin object at 0x00000179143C2278>, username = '13812345678'\ncode = '246810', expect = '叫我老'\n\n    @pytest.mark.parametrize(('username','code','expect'),read_yaml('mp_login.yaml'))\n    def test_mp_login(self,username,code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username,code)\n        # 断言\n        try:\n>           assert expect == self.mp.page_get_nickname()\nE           AssertionError: assert '叫我老' == '叫我老师'\nE             - 叫我老师\nE             ?    -\nE             + 叫我老\n\nscripts\\test01_mp_login.py:41: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test01_mp_login.TestMpLogin object at 0x00000179143C2278>, username = '13812345678'\ncode = '246810', expect = '叫我老'\n\n    @pytest.mark.parametrize(('username','code','expect'),read_yaml('mp_login.yaml'))\n    def test_mp_login(self,username,code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username,code)\n        # 断言\n        try:\n            assert expect == self.mp.page_get_nickname()\n        except Exception as e:\n            log.info(\"断言出错,错误信息: {}\".format(e))\n            print('错误原因:',e)\n            # 截图\n>           self.mp.base_get_img()\n\nscripts\\test01_mp_login.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\base.py:53: in base_get_img\n    self.__base_write_image()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x00000179143F8A58>\n\n    def __base_write_image(self):\n        # 获取图片流\n        with open(\"./image/err.png\", \"rb\") as f:\n            # 调用 allure.attach方法将图片写入报告\n>           allure.attach(\"失败原因：\", f.read(), allure.attach_type.PNG)\nE           AttributeError: module 'allure' has no attribute 'attach_type'\n\nbase\\base.py:60: AttributeError"}, "attachments": [{"name": "log", "source": "591bfc6a-9a35-4149-bdcb-f6b420c4aa2a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "code", "value": "'246810'"}, {"name": "expect", "value": "'叫我老'"}], "start": 1595585852122, "stop": 1595585856209, "uuid": "56d752c4-83ef-45f3-bd2a-a183f2681507", "historyId": "fade3e85370cbf64261f993a50481fec", "testCaseId": "b1928a7174b0d14afd7479ec3844ea33", "fullName": "scripts.test01_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "DESKTOP-IL3MDFO"}, {"name": "thread", "value": "17756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01_mp_login"}]}