{"name": "test_mis_audit", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <scripts.test04_mis_audit.TestMisAudit object at 0x000002B21AF5E748>, title = 'test001-bj001'\nchannel = '数据库'\n\n    def test_mis_audit(self,title=page.title,channel=page.channel):\n        # 调用审核文章业务方法\n>       self.audit.page_mis_audit(title,channel)\n\nscripts\\test04_mis_audit.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npage\\page_mis_audit.py:64: in page_mis_audit\n    self.article_id = self.page_get_article_id()\npage\\page_mis_audit.py:45: in page_get_article_id\n    return self.base_get_text(page.mis_article_id)\nbase\\base.py:42: in base_get_text\n    log.info(\"正在对 {} 元素执行获取文本操作! 获取的文本值: {}\".format(loc,self.base_find(loc).text))\nbase\\base.py:18: in base_find\n    poll_frequency=poll).until(lambda x:x.find_element(*loc)))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"8ce06ebe6eb8bf740616837c3a4975ce\")>\nmethod = <function Base.base_find.<locals>.<lambda> at 0x000002B21AF997B8>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nd:\\python\\python3.6.4\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "attachments": [{"name": "log", "source": "dc5641f6-8659-4750-8175-608296fa4c9a-attachment.txt", "type": "text/plain"}], "start": 1595674208526, "stop": 1595674224559, "uuid": "3e32dc9c-5bde-4fb6-b5e6-085f024c0517", "historyId": "9882f7a913a37e1c698f7c88bfc6c7ef", "testCaseId": "a9c2bf081396218a64bd35d9487692ca", "fullName": "scripts.test04_mis_audit.TestMisAudit#test_mis_audit", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test04_mis_audit"}, {"name": "subSuite", "value": "TestMisAudit"}, {"name": "host", "value": "DESKTOP-IL3MDFO"}, {"name": "thread", "value": "17536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test04_mis_audit"}]}